name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.12']  # Test across multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Firebase credentials
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}  # Add this secret in your GitHub repo settings
      run: |
        echo $FIREBASE_CREDENTIALS > firebase_credentials.json

    - name: Run linting
      run: |
        pip install flake8
        flake8 .  # Lint all files in the project

    - name: Run tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase_credentials.json  # Use Firebase credentials for tests
      run: |
        pytest --disable-warnings

    - name: Upload test coverage
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: reports/
